# Generated by Django 5.1.2 on 2024-10-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankloan',
            old_name='Accno',
            new_name='Accountno',
        ),
        migrations.RenameField(
            model_name='bankloan',
            old_name='Phoneno',
            new_name='mobileno',
        ),
        migrations.RemoveField(
            model_name='bankloan',
            name='Email',
        ),
    ]
